payloads/external/GRUB2: correct Makefile to use revision provided in config
Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>

diff --git a/payloads/external/GRUB2/Makefile b/payloads/external/GRUB2/Makefile
--- a/payloads/external/GRUB2/Makefile
+++ b/payloads/external/GRUB2/Makefile
@@ -13,17 +13,27 @@ MAKEOVERRIDES :=
 
 all: grub2
 
-checkout:
-	echo "    GIT        GRUB2 $(NAME-y)"
-	test -d $(project_dir) || git clone $(project_git_repo) $(project_dir)
-	git -C $(project_dir) fetch
-ifeq ("$(shell test -d $(project_dir) && \
-	(git -C $(project_dir) status --ignored=no --untracked-files=no --porcelain))",)
-	git -C $(project_dir) checkout -f $(TAG-y)
-else
-	echo "WARNING: index/tree not clean, skipping update / force checkout."
-	echo "         Checkout manually with `git -C $(project_dir) checkout -f`."
+clone:
+	echo "    Cloning GRUB2 from Git"
+	git clone $(project_git_repo) $(project_dir)
+
+fetch: clone
+ifeq ($(TAG-y),)
+	echo "Error: The specified tag is invalid"
+ifeq ($(CONFIG_GRUB2_REVISION),y)
+	echo "Error: There is no revision specified for GRUB2"
+	false
 endif
+	false
+endif
+	cd grub2; git show $(TAG-y) >/dev/null 2>&1 ;	if [ $$? -ne 0 ] || \
+		[ "$(TAG-y)" = "origin/master" ]; then \
+		echo "    Fetching new commits from the GRUB2 git repo"; \
+		git fetch; fi
+
+checkout: fetch
+	echo "    Checking out GRUB2 revision $(TAG-y)"
+	cd grub2; git checkout master; git branch -D coreboot 2>/dev/null; git checkout -b coreboot $(TAG-y)
 
 grub2/build/config.h: $(CONFIG_DEP) | checkout
 	echo "    CONFIG     GRUB2 $(NAME-y)"
